version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 & celery -A main.celery worker --loglevel=info"

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"